version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx-dev/Dockerfile
    container_name: nginx
    hostname: nginx
    ports:
      - '80:80'
    networks:
      - backend
    restart: on-failure
    links:
      - api
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/api-dev/Dockerfile
    container_name: api
    hostname: api
    ports:
      - '8000:8000'
    networks:
      - backend
    volumes:
      - $PWD:/home
    restart: on-failure
    environment:
      - DB_HOST=sanic@db:5432
      - DB_NAME=sanic
    tty: true
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:11.3
    container_name: db
    hostname: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=sanic
      - POSTGRES_PASSWORD=sanic
      - POSTGRES_DB=sanic
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    restart: on-failure
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'